"""Structured accessibility rule metadata for the MVP rule engine."""

from __future__ import annotations

from .models import AccessibilityRule

WCAG_2_2_AA = "WCAG 2.2 AA"


RULES: dict[str, AccessibilityRule] = {
    "wcag.document.title": AccessibilityRule(
        id="wcag.document.title",
        standard=WCAG_2_2_AA,
        criterion="2.4.2",
        title="Page Titled",
        level="A",
        requirement="Documents need a clear title or title metadata that describes their topic or purpose.",
        test_method="Check whether the internal document model has a non-empty title.",
        remediation="Add or infer a concise document title and write it into the generated PDF metadata.",
    ),
    "wcag.document.language": AccessibilityRule(
        id="wcag.document.language",
        standard=WCAG_2_2_AA,
        criterion="3.1.1",
        title="Language of Page",
        level="A",
        requirement="The default human language of the document must be programmatically determinable.",
        test_method="Check whether the internal document model has a default language.",
        remediation="Set the generated PDF language metadata after user confirmation if inferred.",
    ),
    "wcag.headings.present": AccessibilityRule(
        id="wcag.headings.present",
        standard=WCAG_2_2_AA,
        criterion="1.3.1",
        title="Info and Relationships",
        level="A",
        requirement="Visual or logical document structure must be represented programmatically.",
        test_method="Check whether a multi-paragraph document has heading elements.",
        remediation="Infer headings from source styles, layout, or user-confirmed AI suggestions.",
    ),
    "wcag.headings.order": AccessibilityRule(
        id="wcag.headings.order",
        standard=WCAG_2_2_AA,
        criterion="1.3.1",
        title="Heading Order",
        level="A",
        requirement="Heading hierarchy should not skip levels in a way that obscures structure.",
        test_method="Check extracted heading levels for unexpected jumps.",
        remediation="Suggest a corrected heading level sequence for user review.",
    ),
    "wcag.images.alt_text": AccessibilityRule(
        id="wcag.images.alt_text",
        standard=WCAG_2_2_AA,
        criterion="1.1.1",
        title="Non-text Content",
        level="A",
        requirement="Meaningful images must have appropriate text alternatives.",
        test_method="Check image elements for alt text or decorative marking.",
        remediation="Generate suggested alt text for meaningful images and ask the user to confirm it.",
    ),
    "wcag.links.meaningful_text": AccessibilityRule(
        id="wcag.links.meaningful_text",
        standard=WCAG_2_2_AA,
        criterion="2.4.4",
        title="Link Purpose",
        level="A",
        requirement="The purpose of each link should be clear from its text or context.",
        test_method="Flag links with empty, URL-only, or generic text.",
        remediation="Suggest clearer link text based on nearby content and URL context.",
    ),
    "wcag.tables.headers": AccessibilityRule(
        id="wcag.tables.headers",
        standard=WCAG_2_2_AA,
        criterion="1.3.1",
        title="Table Relationships",
        level="A",
        requirement="Data tables need identifiable headers and relationships.",
        test_method="Check table elements for extracted header labels.",
        remediation="Infer simple table headers or request user confirmation for complex tables.",
    ),
    "wcag.reading_order.confidence": AccessibilityRule(
        id="wcag.reading_order.confidence",
        standard=WCAG_2_2_AA,
        criterion="1.3.2",
        title="Meaningful Sequence",
        level="A",
        requirement="Content must be presented in a meaningful reading order.",
        test_method="Flag low-confidence extracted elements where reading order may be unreliable.",
        remediation="Ask the user to review the affected section before generating the accessible PDF.",
    ),
    "pdf.tags.present": AccessibilityRule(
        id="pdf.tags.present",
        standard=WCAG_2_2_AA,
        criterion="1.3.1",
        title="Tagged PDF Structure",
        level="A",
        requirement="PDF output must expose meaningful structure programmatically.",
        test_method="Check for a structure tree and marked-content indicator in the source PDF.",
        remediation="Rebuild or repair the PDF with a logical tag tree before final output.",
    ),
    "pdf.extractable_text": AccessibilityRule(
        id="pdf.extractable_text",
        standard=WCAG_2_2_AA,
        criterion="1.4.5",
        title="Images of Text",
        level="AA",
        requirement="Text content should be available as real text except for limited cases.",
        test_method="Check whether the PDF has extractable text blocks.",
        remediation="Run OCR or request a better source document before remediation.",
    ),
    "pdf.reading_order.multicolumn": AccessibilityRule(
        id="pdf.reading_order.multicolumn",
        standard=WCAG_2_2_AA,
        criterion="1.3.2",
        title="Multi-column Reading Order",
        level="A",
        requirement="Content in multi-column PDFs must retain a meaningful reading sequence.",
        test_method="Detect pages whose text block positions appear to form multiple columns.",
        remediation="Review and reconstruct the reading order before generating the accessible PDF.",
    ),
    "pdf.encryption": AccessibilityRule(
        id="pdf.encryption",
        standard=WCAG_2_2_AA,
        criterion="4.1.2",
        title="PDF Is Inspectable",
        level="A",
        requirement="The platform needs permission to inspect and remediate the PDF structure.",
        test_method="Check whether the source PDF is encrypted.",
        remediation="Ask the user for an unlocked PDF or the password before processing.",
    ),
}
